name: "Build"

on:
  push:
    branches:
      - feature/build

jobs:
  build_for_windows:
    name: "Build for Windows"
    runs-on: [windows-2022]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022

      # - name: "Install CUDA"
      #   shell: powershell
      #   run: |
      #     choco install cuda --version=12.0.1.52833 -y
      #     "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin" >> $env:GITHUB_PATH

      - name: "Build"
        shell: cmd
        run: |
          CL.exe /c /I"${{ github.workspace }}\Curl\include" /I"${{ github.workspace }}\OpenCL\include" /Zi /nologo /W1 /WX- /diagnostics:column /O2 /D BUILDING_LIBCURL /D HTTP_ONLY /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"${{ github.workspace }}\dist\\" /Fe"${{ github.workspace }}\dist\\" /external:W1 /Gd /TP /FC /errorReport:prompt Dispatcher.cpp Mode.cpp precomp.cpp profanity.cpp SpeedSample.cpp
          link /out:${{ github.workspace }}\dist\profanity.exe ${{ github.workspace }}\dist\*.obj
        
      - name: "Show Build"
        run: dir ${{ github.workspace }}/dist/*.*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/dist/profanity.exe,${{ github.workspace }}/dist/start.bat,${{ github.workspace }}/dist/profanity.txt"
          token: ${{ secrets.GH_TOKEN }}
          tag: v1.0.3
          draft: true
          allowUpdates: true
          replacesArtifacts: false