name: "Build"

on:
  push:
    branches:
      - feature/build

jobs:
  build_for_windows:
    name: "Build for Windows"
    runs-on: [windows-2022]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022

      - name: "Build"
        shell: cmd
        run: >
          CL.exe 
          /c 
          /I"Curl\include" 
          /I"OpenCL\include" 
          /Zi 
          /nologo 
          /W1 
          /WX- 
          /diagnostics:column 
          /O2 
          /D BUILDING_LIBCURL 
          /D HTTP_ONLY 
          /Gm- 
          /EHsc 
          /MD 
          /GS 
          /fp:precise 
          /Zc:wchar_t 
          /Zc:forScope 
          /Zc:inline 
          /Fo"dist\\" 
          /Fe"dist\\" 
          /external:W1 
          /Gd 
          /TP 
          /FC 
          /errorReport:prompt 
          Dispatcher.cpp Mode.cpp precomp.cpp profanity.cpp SpeedSample.cpp \n\
          link /out:dist\profanity.exe dist\*.obj
        
      - name: "Show Build"
        run: dir ${{ github.workspace }}/dist/*.*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/dist/profanity.exe,${{ github.workspace }}/dist/start.bat,${{ github.workspace }}/dist/profanity.txt"
          token: ${{ secrets.GH_TOKEN }}
          tag: v1.0.3
          draft: true
          allowUpdates: true
          replacesArtifacts: false